/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/gltf-separate/5D FUENSANTICA GLTF.gltf");
  return (
    <group {...props} dispose={null} scale={.6} position={[0, .1, 0]}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["paula"].geometry}
          material={materials.frente}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["paula_1"].geometry}
          material={materials.trasera}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["paula_2"].geometry}
          material={materials.perfil}
        />
      </group>
    </group >
  );
}
//esto es una prueba
useGLTF.preload("/gltf-separate/5D FUENSANTICA GLTF.gltf");